const nodes = [
	{
		id: 0,
		active: true,
		label: 'Старт',
		first: true,
		last: false,
		StartCondition: 0,
		group: 'start',
		level: 0,
		include: true,
	},
	{
		id: 1,
		active: true,
		label: 'Этап 1',
		first: false,
		last: false,
		StartCondition: 0,
		group: 'box',
		level: 1,
		include: true,
	},
	{
		id: 2,
		active: true,
		label: 'Этап 2',
		first: false,
		last: false,
		StartCondition: 0,
		group: 'box',
		level: 1,
		include: true,
	},
	{
		id: 3,
		active: true,
		label: 'Этап 3',
		first: false,
		last: false,
		StartCondition: 3,
		group: 'box',
		level: 2,
		include: true,
	},
	{
		id: 4,
		active: true,
		label: 'Этап 4',
		first: false,
		last: false,
		StartCondition: 0,
		group: 'box',
		level: 2,
		include: true,
	},
	{
		id: 5,
		active: true,
		label: 'Этап 5',
		first: false,
		last: false,
		StartCondition: 0,
		group: 'box',
		level: 3,
		include: true,
	},
	{
		id: 6,
		active: true,
		label: 'Этап 6',
		first: false,
		last: false,
		StartCondition: 1,
		group: 'box',
		level: 3,
		include: true,
	},
	{
		id: 7,
		active: true,
		label: 'Доработка',
		first: false,
		last: false,
		StartCondition: 0,
		group: 'box',
		level: 0.9,
		include: true,
	},
	{
		id: 8,
		active: true,
		label: 'Завершение',
		first: false,
		last: true,
		StartCondition: 2,
		group: 'stop',
		level: 4,
		include: true,
	},
]

const edges = [
	{ id: undefined, from: 0, to: 1, semantic: 8, title: 'Любой исход' },
	{ from: 0, to: 2, semantic: 8, title: 'Любой исход' },
	{ from: 1, to: 3, semantic: 8, title: 'Любой исход' },
	{ from: 3, to: 5, semantic: 8, title: 'Любой исход' },
	{ from: 2, to: 4, semantic: 8, color: 'blue', title: 'Кроме негативного' },
	{ from: 2, to: 6, semantic: 8, color: 'grey', title: 'Нейтральный исход' },
	{ from: 5, to: 8, semantic: 8, color: 'green', title: 'Позитивный исход' },
	{
		from: 5,
		to: 5,
		semantic: 8,
		color: 'red',
		label: '2',
		title: 'Циклы',
		arrows: { from: true, to: false },
		endPointOffset: { from: 6 },
		font: {
			background: 'yellow',
		},
	},
	{ from: 4, to: 6, semantic: 8, color: 'green', title: 'Позитивный исход' },
	{ from: 6, to: 8, semantic: 8, color: 'green', title: 'Позитивный исход' },
	{ from: 6, to: 3, semantic: 8, color: 'red', title: 'Негативный исход' },

	{ from: 9, to: 3, semantic: 8, color: 'blue', title: 'Кроме негативного' },
	{ from: 2, to: 12, semantic: 8, color: 'grey', title: 'Нейтральный исход' },
	// { from: 4, to: 3, semantic: 8 },
	{ from: 2, to: 10, semantic: 8, color: 'red', title: 'Негативный исход' },
	{ from: 4, to: 10, semantic: 8, color: 'red', title: 'Негативный исход' },
	{ from: 7, to: 2, semantic: 8, dashes: true, title: 'Возврат' },
	{ from: 7, to: 4, semantic: 8, dashes: true, title: 'Возврат' },
	// { from: 6, to: 3, semantic: 8, color: 'red' },
	{ from: 10, to: 7, semantic: 8, color: 'blue', title: 'Кроме негативного' },
	{ from: 11, to: 8, semantic: 8, title: 'Любой исход' },
	{ from: 12, to: 6, semantic: 8, title: 'Любой исход' },
]

export { nodes, edges }
