const nodes = [
	{
		id: 0,
		label: 'Старт',
		first: true,
		last: false,
		taskSendingMode: 1,
		repeatMode: 0,
		startConditionType: 0,
		group: 'start',
		level: 0,
	},
	{
		id: 1,
		label: 'Этап 1',
		first: true,
		last: false,
		taskSendingMode: 1,
		repeatMode: 0,
		startConditionType: 0,
		group: 'box',
		level: 1,
	},
	{
		id: 2,
		label: 'Этап 2',
		first: true,
		last: false,
		taskSendingMode: 1,
		repeatMode: 0,
		startConditionType: 0,
		group: 'box',
		level: 1,
	},
	{
		id: 3,
		label: 'Этап 3',
		first: false,
		last: false,
		taskSendingMode: 1,
		repeatMode: 0,
		startConditionType: 3,
		group: 'box',
		level: 3,
	},
	{
		id: 4,
		label: 'Этап 4',
		first: false,
		last: false,
		taskSendingMode: 1,
		repeatMode: 0,
		startConditionType: 0,
		group: 'box',
		level: 3,
	},
	{
		id: 5,
		label: 'Этап 5',
		first: false,
		last: false,
		taskSendingMode: 1,
		repeatMode: 0,
		startConditionType: 0,
		group: 'box',
		level: 5,
	},
	{
		id: 6,
		label: 'Этап 6',
		first: false,
		last: false,
		taskSendingMode: 1,
		repeatMode: 0,
		startConditionType: 1,
		group: 'box',
		level: 5,
	},
	{
		id: 7,
		label: 'Доработка',
		first: false,
		last: false,
		taskSendingMode: 0,
		repeatMode: 0,
		startConditionType: 3,
		group: 'box',
		level: 1,
	},
	{
		id: 8,
		label: 'Завершение',
		first: false,
		last: true,
		taskSendingMode: 0,
		repeatMode: 0,
		startConditionType: 1,
		group: 'stop',
		level: 7,
	},
	{
		id: 9,
		// label: '9 И',
		title: 'id: 9, Логическое И',
		first: false,
		last: false,
		taskSendingMode: 0,
		repeatMode: 0,
		startConditionType: 3,
		group: 'and',
		level: 2,
	},
	{
		id: 10,
		// label: '10 Или',
		title: 'id: 10 Включающее ИЛИ',
		first: false,
		last: false,
		taskSendingMode: 0,
		repeatMode: 0,
		startConditionType: 3,
		group: 'ori',
		level: 2,
	},
	{
		id: 11,
		// label: '11 И',
		title: 'id: 11 Логическое И',
		first: false,
		last: false,
		taskSendingMode: 0,
		repeatMode: 0,
		startConditionType: 3,
		group: 'and',
		level: 6,
	},
	{
		id: 12,
		// label: '12 И',
		title: 'id: 12 Логическое И',
		first: false,
		last: false,
		taskSendingMode: 0,
		repeatMode: 0,
		startConditionType: 3,
		group: 'and',
		level: 4,
	},
]

const edges = [
	{ id: undefined, from: 0, to: 1, semantic: 8, title: 'Любой исход' },
	{ from: 0, to: 2, semantic: 8, title: 'Любой исход' },
	{ from: 1, to: 9, semantic: 8, title: 'Любой исход' },
	{ from: 6, to: 9, semantic: 8, color: 'red', title: 'Негативный исход' },
	{ from: 9, to: 3, semantic: 8, color: 'blue', title: 'Кроме негативного' },
	{ from: 2, to: 4, semantic: 8, color: 'blue', title: 'Кроме негативного' },
	{ from: 2, to: 12, semantic: 8, color: 'grey', title: 'Нейтральный исход' },
	// { from: 4, to: 3, semantic: 8 },
	{ from: 4, to: 12, semantic: 8, color: 'green', title: 'Позитивный исход' },
	{ from: 2, to: 10, semantic: 8, color: 'red', title: 'Негативный исход' },
	{ from: 4, to: 10, semantic: 8, color: 'red', title: 'Негативный исход' },
	{ from: 7, to: 2, semantic: 8, dashes: true, title: 'Возврат' },
	{ from: 7, to: 4, semantic: 8, dashes: true, title: 'Возврат' },
	// { from: 6, to: 3, semantic: 8, color: 'red' },
	{ from: 6, to: 11, semantic: 8, color: 'green', title: 'Позитивный исход' },
	{ from: 3, to: 5, semantic: 8, title: 'Любой исход' },
	{ from: 5, to: 11, semantic: 8, color: 'green', title: 'Позитивный исход' },
	{ from: 10, to: 7, semantic: 8, color: 'blue', title: 'Кроме негативного' },
	{ from: 11, to: 8, semantic: 8, title: 'Любой исход' },
	{ from: 12, to: 6, semantic: 8, title: 'Любой исход' },
]

export { nodes, edges }
