const nodes1 = [
	{
		id: 0,
		active: true,
		label: 'Старт',
		title: 'Согласование договоров (ДП)',
		desc: 'Маршрут используется для согласования общих договоров с подписанием.',
		first: true,
		last: false,
		StartCondition: 0,
		group: 'start',
		level: 0,
		start: [''],
	},
	{
		id: 1,
		active: true,
		label: 'Этап 1',
		first: false,
		last: false,
		StartCondition: 0,
		group: 'box',
		level: 1,
		start: [{ icon: 0, title: 'Старт согласования' }],
	},
	{
		id: 2,
		active: true,
		label: 'Этап 2',
		first: false,
		last: false,
		StartCondition: 2,
		group: 'box',
		level: 1,
		start: [
			{ icon: 1, title: 'Старт согласования' },
			{ icon: 1, title: '{Доработка} возврат' },
		],
	},
	{
		id: 3,
		active: true,
		label: 'Этап 3',
		first: false,
		last: false,
		StartCondition: 2,
		group: 'box',
		level: 2,
		start: [
			{ icon: 1, title: '{Этап 1} завершен' },
			{ icon: 1, title: '{Этап 6} негативный исход' },
		],
	},
	{
		id: 4,
		active: true,
		label: 'Этап 4',
		first: false,
		last: false,
		StartCondition: 2,
		group: 'box',
		level: 2,
		start: [
			{ icon: 1, title: '{Этап 2} завершен не негативно' },
			{ icon: 1, title: '{Доработка} возврат' },
		],
	},
	{
		id: 5,
		active: true,
		label: 'Этап 5',
		first: false,
		last: false,
		StartCondition: 0,
		group: 'box',
		level: 3,
		start: [{ icon: 0, title: '{Этап 3} завершен' }],
	},
	{
		id: 6,
		active: true,
		label: 'Этап 6',
		first: false,
		last: false,
		StartCondition: 1,
		group: 'box',
		level: 3,
		start: [
			{ icon: 0, title: '{Этап 2} завершен нейтрально' },
			{ icon: 0, title: '{Этап 4} завершен положительно' },
		],
	},
	{
		id: 7,
		active: true,
		label: 'Доработка',
		first: false,
		last: false,
		StartCondition: 2,
		group: 'box',
		level: 1,
		start: [
			{ icon: 1, title: '{Этап 2} завершен отрицательно' },
			{ icon: 1, title: '{Этап 4} завершен отрицательно' },
		],
	},
	{
		id: 8,
		active: true,
		label: 'Завершение',
		first: false,
		last: true,
		StartCondition: 2,
		group: 'stop',
		level: 4,
		start: [''],
	},
]

const edges1 = [
	{ id: undefined, from: 0, to: 1, semantics: 8, title: 'Любой исход' },
	{ from: 0, to: 2, semantics: 8, title: 'Любой исход' },
	{ from: 1, to: 3, semantics: 8, title: 'Любой исход', endPointOffset: { to: 10 } },
	{ from: 3, to: 5, semantics: 8, title: 'Любой исход' },
	{ from: 2, to: 4, semantics: 8, color: 'blue', title: 'Кроме негативного' },
	// { from: 2, to: 7, semantics: 8, color: 'red', title: 'Негативный исход' },
	// { from: 4, to: 7, semantics: 8, color: 'red', title: 'Негативный исход' },
	{
		from: 2,
		to: 6,
		semantics: 8,
		color: 'grey',
		title: 'Нейтральный исход',
		endPointOffset: { to: 10 },
	},
	{ from: 5, to: 8, semantics: 8, color: 'green', title: 'Позитивный исход' },
	{
		from: 5,
		to: 5,
		semantics: 8,
		color: 'red',
		label: '2',
		title: 'Циклы',
		arrows: { from: true, to: false },
		endPointOffset: { from: 6 },
		font: {
			background: 'yellow',
		},
	},
	{
		from: 4,
		to: 6,
		semantics: 8,
		color: 'green',
		title: 'Позитивный исход',
		endPointOffset: { to: 10 },
	},
	{ from: 6, to: 8, semantics: 8, color: 'green', title: 'Позитивный исход' },
	{ from: 6, to: 3, semantics: 8, color: 'red', title: 'Негативный исход' },

	{
		from: 7,
		to: 2,
		semantics: 8,
		dashes: true,
		title: 'Возврат',
		arrows: { from: true, to: true },
	},
	{
		from: 7,
		to: 4,
		semantics: 8,
		dashes: true,
		title: 'Возврат',
		arrows: { from: true, to: true },
	},
]

export { nodes1, edges1 }
