const nodes2 = [
	{
		id: 0,
		active: true,
		label: 'Старт',
		first: true,
		last: false,
		StartCondition: 0,
		group: 'start',
		title: 'Согласование группой ответственных договора ДВ-Заказчик (свыше 100 т.р.)',
		desc: 'Маршрут используется для согласования договоров с поставщиками ДВ-Заказчик, с суммой больше 100 т.р',
		taskSendingMode: 0,
		repeatMode: 0,
		start: [''],
	},
	{
		id: 1,
		active: true,
		label: 'Консолидация 2-Н',
		first: false,
		last: false,
		group: 'box',
		taskSendingMode: 0,
		repeatMode: 0,
		StartCondition: 0,
	},
	{
		id: 2,
		active: true,
		label: 'Согласование в ГК 2',
		first: false,
		last: false,
		group: 'box',
		taskSendingMode: 0,
		repeatMode: 0,
		StartCondition: 0,
	},
	{
		id: 3,
		active: true,
		label: 'Согласование с контрагентом',
		first: false,
		last: false,
		group: 'box',
		taskSendingMode: 0,
		repeatMode: 0,
		StartCondition: 3,
	},
	{
		id: 4,
		active: true,
		label: 'Подписание 2',
		first: false,
		last: false,
		group: 'box',
		taskSendingMode: 0,
		repeatMode: 0,
		StartCondition: 3,
	},
	{
		id: 5,
		active: true,
		label: 'Подписание контрагентом 2',
		first: false,
		last: false,
		group: 'box',
		taskSendingMode: 0,
		repeatMode: 0,
		StartCondition: 0,
	},
	{
		id: 6,
		active: true,
		label: 'Консолидация 3',
		first: false,
		last: false,
		group: 'box',
		taskSendingMode: 0,
		repeatMode: 0,
		StartCondition: 3,
	},
]

const edges2 = [
	{
		id: undefined,
		semantics: 2,
		color: 'red',
		from: 0,
		to: 1,
	},
	{
		semantics: 3,
		color: 'grey',
		from: 6,
		to: 2,
	},
	{
		semantics: 1,
		color: 'green',
		from: 6,
		to: 3,
	},
	{
		semantics: 1,
		color: 'green',
		from: 2,
		to: 3,
	},
	{
		semantics: 1,
		color: 'green',
		from: 3,
		to: 4,
	},
	{
		semantics: 3,
		color: 'grey',
		from: 3,
		to: 4,
	},
	{
		semantics: 1,
		color: 'green',
		from: 4,
		to: 5,
	},
	{
		semantics: 1,
		color: 'green',
		from: 0,
		to: 6,
	},
	{
		semantics: 3,
		color: 'grey',
		from: 0,
		to: 6,
	},
]

export { nodes2, edges2 }
